name: local-rag
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - atk-1.0=2.36.0
  - beautifulsoup4=4.12.3
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.16.0
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - cryptography=43.0.0
  - et_xmlfile=1.1.0
  - expat=2.6.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.8
  - gettext=0.21.1
  - ghostscript=9.54.0
  - giflib=5.2.2
  - graphite2=1.3.13
  - graphviz=3.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=4.3.0
  - icu=70.1
  - imagemagick=7.1.0_35
  - jbig=2.1
  - jpeg=9e
  - lcms2=2.14
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgd=2.3.3
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libiconv=1.17
  - libnsl=2.0.1
  - libpng=1.6.43
  - librsvg=2.54.4
  - libsqlite=3.46.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libtool=2.4.7
  - libuuid=2.38.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.10.3
  - libxslt=1.1.37
  - libzlib=1.2.13
  - lxml=4.9.2
  - lz4-c=1.9.3
  - markdown2=2.4.0
  - ncurses=6.4
  - openjpeg=2.5.0
  - openpyxl=3.1.5
  - openssl=3.3.1
  - pango=1.50.7
  - pcre2=10.43
  - pdfminer.six=20221105
  - pdfplumber=0.9.0
  - perl=5.32.1
  - pillow=9.2.0
  - pip=24.0
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pthread-stubs=0.4
  - pycparser=2.22
  - python=3.11.8
  - python-docx=1.1.2
  - python_abi=3.11
  - readline=8.2
  - setuptools=72.1.0
  - soupsieve=2.5
  - sqlite=3.45.3
  - tk=8.6.14
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wand=0.6.10
  - wheel=0.43.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.2
prefix: /home/alex/miniconda3/envs/local-rag
